### ISSUE TITLE
hexo deploy 导致所有 commit 丢失

### ISSUE THREAD

**Issue by oovm** [GalAster/Galaster.github.io#2]
**Noooooooooooooo!**

**All my commits lost !!!**

---

- [x] fix this stupid problem

**Comment by oovm** [comment]
ref: https://github.com/hexojs/hexo/issues/3002

`overwrite` 看起来就是直接复写了整个记录

保险起见应该自己写部署函数 🤕

**Comment by oovm** [comment]
好像没别的好办法, 不如手动同步...滑稽

```sh
# 不会丢失 commit history 的部署方式
rm .deploy_git -r -f &&
hexo clean && hexo g --silent &&
git clone https://github.com/GalAster/Galaster.github.io .deploy_git &&
cd .deploy_git && git checkout master &&
cd ../ && mv .deploy_git/.git/ ./public/ &&
cd ./public && git add . &&
git commit -m "Site updated at  `date +"%Y-%m-%d %H:%M"` :octocat:" &&
git push --force https://github.com/GalAster/Galaster.github.io master:master
```

**Comment by oovm** [comment]
https://github.com/GalAster/Galaster.github.io/commit/9ad512850998e0092853b16cabc57a61e8f0685c 测试成功, 接下来进行 Travis CI 测试

**Comment by oovm** [comment]
https://github.com/GalAster/Galaster.github.io/commit/0e485bf181f2e4d0989a60618fd4c29f59041f84 集成完成

问题解决 💯

**Comment by oovm** [comment]
不行, 国内 gayhub 网速太慢, 这样子每次都要同步太吃力

可能我要去看看别人的 travis 怎么写的

- [x] 备用的快速部署方案

- [ ] 搞明白到底什么导致了 commits 历史丢失

- [x] 正确的 travis 配置

**Comment by oovm** [comment]
比原来稍快的方案

```sh
mkdir .deploy && cd .deploy &&
git clone --depth 1 --branch master --single-branch https://github.com/GalAster/Galaster.github.io.git . &&
rm -rf ./* && cp -r ../public/* . &&
git add -A . && - git commit -m "Site updated at  `date +"%Y-%m-%d %H:%M"` :octocat:" &&
git branch -m master && git push -q -u origin master
```

**Comment by oovm** [comment]
## git_key尝试无效

https://github.com/GalAster/Galaster.github.io/blob/d8b92b0992a91b888caaf9f9d7330db498ca8419/.travis.yml#L22-L25

仍然吃光了我的 commit history.

不知道用 ssh-key 能不能解决这个问题, 但我懒得保管ssh-key了, 就这样算了吧...

## 放弃使用 hexo deploy

速度问题只在国内比较明显, 因为 git clone 在国内只有4k, 不然`depth=1`才 2MB 的小文件一秒都不到, 非常的迅速.

官方看起来拒绝取消 `force push`, 那我只能放弃使用 `hexo deploy`. 
https://github.com/hexojs/hexo-deployer-git/issues/33 
https://github.com/hexojs/hexo/issues/2378



可怜我之前的 commit 滑稽 👎  ...

讲道理, 放着也没啥用...

**Comment by qiwihui** [comment]
遇到释怀样的问题，看见你的issue。以下是在 `master` 分支提交后向 `gh-pages` 部署 pages 的配置，保留提交历史：

`.travis.yml`:

```yaml
deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: master
env:
  global:
  - secure: YQjZubH......
```

`deploy.sh`:

```sh
#!/bin/bash

# Initialize target with currently deployed files
git clone --depth 1 --branch=gh-pages https://github.com/qiwihui/blog.git .deploy_git

cd .deploy_git

# Remove all files before they get copied from ../public/
# so git can track files that were removed in the last commit
find . -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null

cd ../

# Run deployment
hexo clean
hexo generate --deploy --quiet
```

详细可见 [qiwihui/blog](https://github.com/qiwihui/blog)
